### ISSUE TITLE
Faucets (white, gold, and kitchen) no longer empty into kitchen "cabinet" sinks

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/homedecor_modpack#302]
I recently updated homedecor on my server along with signs_lib when it was created. I noticed that the faucets seem to be more intelligent and only run when there's a sink or shower drain below it (not sure if you intentionally did that but I'd imagine you would have).

However, nothing empties into either of the kitchen "cabinet" sinks (locked or unlocked). This is true of the white faucet, the gold faucet, and the kitchen faucet.

**Comment by redblade7** [comment]
Upon a second glance it appears to dispense over the unlocked kitchen cabinet sinks, but not the locked ones.

**Comment by kaeza** [comment]
Fixed by 1ea19fd12fdf6685eaaf13113e31b0494bafa790.

Thank you for reporting!
