### ISSUE TITLE
Suggestion - Add Log Recording of Items Moved to and From Chests

### ISSUE THREAD

**Issue by LazyJ** [minetest-mods/homedecor_modpack#307]
**Minetest Game commit:**  [Add Item Name to Chest Log Messages - 42cc6d2](https://github.com/minetest/minetest_game/commit/42cc6d2c311d4b70f328d3e31554bf90dd9fc45e)

A recent update to the default chest and locked_chests records what items a player puts in the chest and takes from the chest. Such info is useful for identifying thieves. Would it be possible to add this log recording ability to all the various locked and unlocked containers in HomeDecor?

**Comment by sofar** [comment]
Trivial.

Someone just needs to write a patch, this is totally outside of my time right now, care to try?
