### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/homedecor_modpack#312]
Hi,

the LICENSE files says models, textures and sounds are CC-BY-SA-3.0 or higher, and then the text of CC-BY-SA-4.0 is given. There are also credits given in the README that don't appear in the LICENSE file, so I'm not quite sure which files are covered by which copyright.

I'm asking because I'm pondering packaging homedecor for Debian and I'll need those copyright issues clearly sorted out if I want that to happen! [Note that I'll probably also ask later for a proper release for the same reasons]

Thanks!

PS: this is an example of what I have to produce before a package can get in: [a Debian copyright](https://anonscm.debian.org/git/pkg-games/minetest-mod-nether.git.git/tree/debian/copyright)

**Comment by VanessaE** [comment]
I specified "CC-by-SA 3.0 or later" in the forum post for this modpack, so the text actually being from 4.0 is technically valid; I guess you can consider the "3.0" as a typo or oversight..  In my opinion anyways.

**Comment by sofar** [comment]
Note that copies of license texts are *never* a declaration of license. The line that says "licensed under xxx" is the only thing that matters.
