### ISSUE TITLE
Furniture inventory is unprotected

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/homedecor_modpack#313]
I discovered that you can actually transfer stuff from/to homedecor's furniture in areas protected by "protector redo" of other players :) Not good.

**Comment by t4im** [comment]
Are you sure this happens for **locked** furniture? The unlocked ones are of course not protected from inventory transfer.

**Comment by Fixer-007** [comment]
I've paniced because I was playing on server without locked ones that were removed by server owner.
Case closed, everything is good :)
