### ISSUE TITLE
[Patch] Replace Deprecated "maxwear=0.01" with "uses='maxwear'"

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/homedecor_modpack#316]
I wanted to suggest the following patch that replaces "maxwear=0.01" with "uses='maxwear'". Not 100% sure if it is correct, but it removes the deprecated field warning.

[mod-building_blocks__init.lua.diff.zip](https://github.com/minetest-mods/homedecor_modpack/files/416024/mod-building_blocks__init.lua.diff.zip)

**Comment by sofar** [comment]
diffs shouldn't be uploaded as zip file like this. Please just copy and paste the diff as text instead, or better, make an actual change or PR.
