### ISSUE TITLE
After recent update all is white

### ISSUE THREAD

**Issue by 00c** [minetest-mods/homedecor_modpack#343]
Sofas, banister, chairs, table all is white.

**Comment by 00c** [comment]
When i dig banister it turns into correct color, Everything rest is only white craftable.

**Comment by VanessaE** [comment]
Banisters and tables were not changed recently.   For the other stuff, you just need to place the white object, wield some dye, and right-click to change its color.

**Comment by VanessaE** [comment]
See the various commits after Jan 29.
