### ISSUE TITLE
Doors 

### ISSUE THREAD

**Issue by 00c** [minetest-mods/homedecor_modpack#344]
Could you please make doors act as half door 
So if you open one the other one above or below opens too similar as half door from cottages mod.

**Comment by VanessaE** [comment]
This is not really possible to do with the doors in this mod, however, there are gates that act in a similar manner.  It wouldn't be too much trouble to add a few variations that look more like a half-door.

**Comment by VanessaE** [comment]
0ff3013895370a9108404dc764479ee798a0ea03
