### ISSUE TITLE
Desk lamp wrong placement (possibly others)

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/homedecor_modpack#346]
Desk_lamp, writable book and possibly other nodes are placed in wrong manner:

![lamp](https://cloud.githubusercontent.com/assets/16494741/23106008/f6ad7d78-f6ef-11e6-9639-589202afc751.png)

**Comment by VanessaE** [comment]
Works fine for me.
![screenshot - 02202017 - 01 29 55 am](https://cloud.githubusercontent.com/assets/1733537/23114270/1b2cf518-f70c-11e6-9dfa-da84d8e0c0b5.png)

**Comment by VanessaE** [comment]
Probably related to your Unified dyes being out of date

**Comment by Fixer-007** [comment]
Yep, can confirm.
