### ISSUE TITLE
Needs activation via right-click

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/homedecor_modpack#347]
Those nodes use on_punch for changing their state (left click):
- [X] toilet
- [X] toilet_open
- [X] desk_fan
- [X] doorbell
- [X] speaker
- [X] speaker_open
- [X] beer_tap - ~~unclear what it does, please check~~  (it takes away an empty vessels drinking glass if you're wielding it, and replaces it with a full mug of beer.  --VanessaE)
- [x] soda_machine (accepts coin with left click)
- [x] ceiling_lamp
- [x] ceiling_lamp_off
- [x] plasmascreen:tv
- [x] plasmascreen:tv_off

I left out nodes that are activated with left click and have formspec on right: medicine_cabinet, book, trashcan...

**Comment by VanessaE** [comment]
vanessa@rainbird:~/Minetest-related/mods/my_mods/homedecor_modpack$ git log
commit f09481c3f0df73339060da05f5135c9d7885c522

**Comment by Fixer-007** [comment]
I will look into beer_tap more, I had some suspicion about it.

**Comment by VanessaE** [comment]
There's nothing to look into, it just works. :-)

**Comment by Fixer-007** [comment]
https://github.com/minetest-mods/homedecor_modpack/issues/350
