### ISSUE TITLE
Add unified dyes into this modpack

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/homedecor_modpack#348]
Since it is a dependancy now, and homedecor is modpack anyway, please add unifieddyes into it.

If you won't - then update Readme.txt (Dependencies part)

**Comment by kaeza** [comment]
TBH, I don't really like UD being a hard dependency, and I'm sure there's a way to not depend on it.

Please let's not add unrelated stuff to this MP.

**Comment by VanessaE** [comment]
Unified Dyes does not belong in this modpack - it's supposed to be home-and-building decor, and it's trivial to obtain and install UD.
