### ISSUE TITLE
Irfurn: need weild image in hand

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/homedecor_modpack#352]
It looks incorrect in hand right now

Affected:
* irfurn:sofa
* irfurn:longsofa
* irfurn:armchair

**Comment by VanessaE** [comment]
There's no way to change how the engine presents the model in-hand, and a wield image won't look right because it's extruded and turned at an odd angle.

**Comment by VanessaE** [comment]
It may not be a proper fix, but this will help a tiny bit, 2c034ebba0163bc7e60e26b7cc934d1934680887  (smaller visual scale so the wielded mesh isn't "up in your face")
