### ISSUE TITLE
Physics shape not matching visual shape in some objects

### ISSUE THREAD

**Issue by pgimeno** [minetest-mods/homedecor_modpack#356]
Detected with lrfurn's armchair, others may be affected. Affects current master as of this writing. Not sure if it's a Minetest or homedecor problem.

To reproduce:

- Face north.
- Create a lrfurn armchair.
- Observe that you can climb through it as if it was a stairs block by going forward.
- Now face south.
- Create another one (or take that one and spawn it again).
- Observe that you can no longer climb through it by going forward.
- Observe that you can however climb it from the south, where the back of the armchair is.

This didn't happen with release 0.4.15.

**Comment by VanessaE** [comment]
This is an engine bug I've run into before, https://github.com/minetest/minetest/issues/2612

...guess it's not limited to over-one-meter objects anymore.

**Comment by pgimeno** [comment]
Thanks. Consider the possibility that it might be a different issue, as it doesn't happen with minetest current head but an older version of homedecor.

**Comment by VanessaE** [comment]
It might be triggered by the fact that those armchairs are "colorwallmounted" now.
