### ISSUE TITLE
it seems to still give me issues with the building_blocks

### ISSUE THREAD

**Issue by astrayar** [minetest-mods/homedecor_modpack#361]
I have moreblocks but its still not working with building_blocks it worked once then stopped and now just errors out so all i can do is take the building_blocks out which takes tons i like about the pack poofed sigh! if this helps here is the pic of the error
![screenshot from 2017-03-15 12-37-25](https://cloud.githubusercontent.com/assets/21336494/23959811/8ba782b8-097c-11e7-8003-4b3de7dc454c.png)

**Comment by astrayar** [comment]
the mod pack is home_decor for minetest  sigh!

**Comment by VanessaE** [comment]
Update your minetest engine build.  Version 0.4.13 is far too old for this modpack.

**Comment by astrayar** [comment]
ok how do i do that i have tried and it keeps only allowing this version Download Page for minetest_0.4.13+repack-1build1_amd64.deb on AMD64 machines for ubuntu to work

**Comment by VanessaE** [comment]
Either use the [daily builds PPA](https://launchpad.net/~minetestdevs/+archive/ubuntu/daily-builds), or build it from the source code from [the official git repository](https://github.com/minetest/minetest).

Consider updating your OS if you still can't get anything newer.
