### ISSUE TITLE
almost-forgotten requests for more items, random stuff

### ISSUE THREAD

**Issue by VanessaE** [minetest-mods/homedecor_modpack#362]
This issue is just so I don't forget some random stuff that's been requested or discussed either recently or in the past.. I actually skimmed back to mid-2015 looking for stuff I missed.

- [ ] The bathtub needs better collision boxes so that the user can climb in.
- [ ] bathroom taps need to be modified to look for bathtubs when the user attempts to turn them on.
- [ ] taps and faucets need to create some kind of ID for the particle stream so that they can turn on/off more reliably.
- [ ] building a table from separate "legs" and "top" nodes should cause homedecor to combine them into one node (like signs_lib does with a sign on a wooden fencepost).
- [ ] The cubical plasma lamp needs to be re-made to use a mesh node instead of the framed glass drawtype.
- [ ] User Andrey01 requests "modern" bathtubs and stools.  By bathtubs, I assume he means the rather boring, rectangular, shallow kind of bathtub with tall plastic walls, usually embedded into the walls in the bathroom.  By stools, he means something equivalent to removing the back from a kitchen chair (padded or regular).
- [ ] He also requested another type of mirror, but the only thing I can think that needs added is a version of the bathroom medicine cabinet that has steel or brass taps under it.
- [ ] He also requests a rocking chair.
- [ ] He also requested "more [different] types of wardrobes, cupboards, tables, desks, doors and windows"
- [ ] He also requested more types of chandeliers and lamps.
- [ ] User TumeniNodes requested a toilet of the old type with a separate, elevated tank operated by a pull-chain.
- [ ] User amadin requested that the `inbox` mailbox show a raised flag when the user has mail.
- [ ] User DoyleChris requested nodes with drywall/sheet-rock on one side.
- [ ] User Inocudom requested an "antique" radio.
- [ ] User LazerRay requested an ottoman/footstool.

**Comment by kaeza** [comment]
>building a table from separate "legs" and "top" nodes should cause homedecor to combine them into one node (like signs_lib does with a sign on a wooden fencepost).

If somebody can do a suitable model, I can take care of the coding.

>He also requested another type of mirror, but the only thing I can think that needs added is a version of the bathroom medicine cabinet that has steel or brass taps under it.

Maybe he means one of these:

* http://i.dailymail.co.uk/i/pix/2013/07/26/article-2378768-1B0030EC000005DC-472_634x857.jpg
* https://s-media-cache-ak0.pinimg.com/736x/4b/7f/81/4b7f811508e14bd89ed184ff7390d51e.jpg
* http://rk.pbimgs.com/pbimgs/rk/images/dp/wcm/201712/0034/nora-pieced-antiqued-mirror-o.jpg

**Comment by VanessaE** [comment]
OOPS

**Comment by VanessaE** [comment]
The official repo for this project has been moved to Gitlab.  https://gitlab.com/VanessaE/homedecor_modpack/issues
