### ISSUE TITLE
Colored books are now unknown blocks

### ISSUE THREAD

**Issue by bulldog1** [minetest-mods/homedecor_modpack#363]
The colored books that were used in VE-Creative are now unknown blocks. This should not happen, and I would just like to claim the data that these books hold. 

Thanks.

**Comment by VanessaE** [comment]
This is a bug in homedecor, sorta.

I believe the correct solution here is threefold:
1. Add colored itemstack and item metadata support to Unified Inventory.
2. Re-add the original colored book nodes, but keep them out of the creative inventory.
3. Add a tweak to cause the original colored books to be replaced with neutral-but-colorized versions on-place.

**Comment by redblade7** [comment]
Oh man. I wish we would have been warned about 0.4.16 breaking stuff before we upgraded our servers.

**Comment by VanessaE** [comment]
This isn't a Minetest engine or game issue, it's something I turned off in Homedecor back in January with commit 3969f1a19836300e723c1bf379f3df6ddfc77989.  It'll be turned on when I or someone else fixes how Homedecor interacts with minetest_game.

**Comment by redblade7** [comment]
"Writable book" is visible in unified_inventory and can be dyed by punching, but only by the admin account. It is not visible in user accounts and is an unknown item for them.

**Comment by redblade7** [comment]
VanessaE: you pasted the commit for the beds/sleeping issue. Writable books are still in the game, though not working correctly (according to whata both bulldog1 and I described).

**Comment by VanessaE** [comment]
Correct.  the books will be fixed soon-ish.

**Comment by VanessaE** [comment]
21911d14631d8f28ce81d9a3c9ae843e534fb1a8
