### ISSUE TITLE
Plasma items don't work anymore after v0.4.16

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/homedecor_modpack#368]
The plasma items don't work under v0.4.16. This is the case both when using an 0.4.15-era (pre-param2/dyes api) version of homedecor_modpack as well as a more recent version of homedecor_modpack.

The plasma crystal ball has a white holder instead of a black one and cannot be switched on/off.

The plasma square lamp is just a see-through block, it does not have the rainbow animation.
![screenshot_20170605_013618](https://cloud.githubusercontent.com/assets/15269155/26771956/843cbab2-4990-11e7-8ea6-b97ca727e327.png)

Screenshot attached.

**Comment by VanessaE** [comment]
fixed with b05d3eb57d595ae5d1fdebe0ab1a16fbad7f191b and bd70955a9b0cc082400db11d1431bce6bbfd0aab
