### ISSUE TITLE
Release request (0.4.16)

### ISSUE THREAD

**Issue by diogo-gomes** [minetest-mods/homedecor_modpack#369]
@VanessaE,

Can you create a release with tag **0.4.16**?

[Bower](https://bower.io/) and [Minetest Bower](https://minetest-bower.herokuapp.com) not update your mod without it.

Thanks

**Comment by VanessaE** [comment]
I'll do that soon-ish.  There are a few bugs I need to fix first, and a bunch of new items I want to add.

**Comment by VanessaE** [comment]
Let's keep this open so that I don't forget it.

**Comment by diogo-gomes** [comment]
Okay, sorry.

**Comment by VanessaE** [comment]
https://github.com/minetest-mods/homedecor_modpack/releases/tag/0.4.16
