### ISSUE TITLE
building_blocks:fakegrass missing in HEAD?

### ISSUE THREAD

**Issue by ensonic** [minetest-mods/homedecor_modpack#370]
I was using '0.4.15' and tried both 'stable-20170228' and 'head'. With those I've got

    ERROR[Server]: Item "building_blocks:fakegrass" not defined

Not sure how I ended up using this in my world instead of the normal `default:dirt_with_grass`. If you can confirm that it was removed, I can try to use worldedit to fixup my kids worlds. Maybe you can mention such fixup procedures in the release notes or tell me what I did wrong :)

**Comment by VanessaE** [comment]
some other mod must be trying to redefine it, maybe, as it is definitely present in building_blocks: 
 https://github.com/minetest-mods/homedecor_modpack/blob/master/building_blocks/init.lua#L516

**Comment by ensonic** [comment]
Thanks for the quick reply. Will need to debug a bit further. None of my mods redefines it (did a `find . -type f -exec grep -Hn "fakegrass" {} \;` in my mod folder). Also the lines related to fakegrass in `building_blocks/init.lua` are unchanged, although my issue is reproducable ...

**Comment by VanessaE** [comment]
I can't reproduce this error in Dreambuilder, so it's gotta be something on your end.  In fact the only way I could get that error to show up is if I punch an undefined node, so I have to assume it's the result of the mod having been removed from your environment.

**Comment by ensonic** [comment]
The missing block seems to be in homedecor_i18n, but when I enable this I got:
```
2017-06-16 22:02:49: ERROR[Main]: ModError: Failed to load and run script from /home/ensonic/.minetest/mods/homedecor_modpack/building_blocks/init.lua:
2017-06-16 22:02:49: ERROR[Main]: ...minetest/mods/homedecor_modpack/building_blocks/init.lua:336: bad argument #1 to 'ipairs' (table expected, got nil)
2017-06-16 22:02:49: ERROR[Main]: stack traceback:
2017-06-16 22:02:49: ERROR[Main]: 	[C]: in function 'ipairs'
2017-06-16 22:02:49: ERROR[Main]: 	...minetest/mods/homedecor_modpack/building_blocks/init.lua:336: in main chunk
```

after updating `moreblocks`, the error was fixed.
