### ISSUE TITLE
Core file in 0.4.16 tarball

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/homedecor_modpack#371]
Hi, the 0.4.16 tarball on github contains a core file... I'm pretty sure it has nothing to do here!

I saw it while trying to update my Debian package.

**Comment by VanessaE** [comment]
fixed.  No idea how that even got in there!

**Comment by kaeza** [comment]
This is why you should never do `git add .`, and add files individually one at a time.

You should seriously consider [this GH article](https://help.github.com/articles/removing-sensitive-data-from-a-repository/).

**Comment by VanessaE** [comment]
meh, it's old habit I guess.  Anyway, ran the tool recommended there and got rid of the core from the repo history.  I'm not worried, it was just a core dump of minetest itself anyway.

**Comment by kaeza** [comment]
It was not only about sensitive data, but adding 1.5MB of unneeded bloat to an already overbloated repo.

It still seems the blob is [accessible](https://github.com/minetest-mods/homedecor_modpack/blob/bdcfe9678df889cd23867b708f35505ed7bf2412/core) from Github. Not sure if that is also downloaded when you clone, but you should probably nuke that commit too.

**Comment by VanessaE** [comment]
I've managed to remove that commit from my local repo for sure now, and can no longer make it show up with, for example, `git log --all --full-history -- core` nor with `git show` and that commit ID... but no matter what I do, I can't get Github to forget about that commit.
