### ISSUE TITLE
Chess tiles don't show chess pattern is you use more than 1

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/homedecor_modpack#374]
The chess tile does not show a chess pattern if you place more than one of these on the floor next to each other.
The tiles just “randomly” rotate for some reason.

**Comment by VanessaE** [comment]
Which tile is that? If you mean building_blocks' BWtile, that uses the raillike draw type, so it's kinda finicky.

**Comment by Wuzzy2** [comment]
Yes, exactly. I already suspected `raillke` as drawtype, it feels *very* wrong to use this for a floor tile.

**Comment by VanessaE** [comment]
When the building_blocks mod was first made years ago, nodeboxes and mesh nodes didn't exist.  I guess raillike was the only way to make it work.  I'll make it a nodebox soon-ish.

**Comment by VanessaE** [comment]
c60607aa0d27e6eda79f04e12469081f641df190
