### ISSUE TITLE
Inappropriate/missing sounds for many nodes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/homedecor_modpack#375]
Many blocks either lack node sounds (dig/dug/footstep/etc.) or have incorrect sounds (e.g. wooden or even leaf sounds when it should be metal).

There are too many nodes to list, here are just a two examples:
* Roof block
* Grate

Hint 1: Use `qa_block` to find missing sounds and other mistakes:
https://forum.minetest.net/viewtopic.php?f=11&t=15759&p=238851
It's very useful for QA.

Hint 2: Minetest Game has metal sounds.

EDIT: Damn! `qa_block` doesn't have sound checks yet. Will add them as soon as I can. Sorry. :-(

EDIT 2: `qa_block` now has a sound check.

**Comment by VanessaE** [comment]
There are hundreds of nodes in this modpack, too many for me to deal with anytime soon, but I'd welcome a suitable pull request.

**Comment by Jat15** [comment]
@Wuzzy2 
Not sound with slabs and stairs ?
#387

**Comment by Jat15** [comment]
Grate and Roof #393

**Comment by VanessaE** [comment]
The official repo for this project has been moved to Gitlab.  Please copy/paste/re-open your issue over there.  https://gitlab.com/VanessaE/homedecor_modpack/issues
