### ISSUE TITLE
Duplicated flint and steel

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/homedecor_modpack#376]
The flint and steel is a duplicate, it already exists in Minetest Game.

**Comment by VanessaE** [comment]
A known issue.  This flint-and-steel object predates the one in minetest_game; there are a few other items here and there in my mods that need similarly aliased-out.

**Comment by Wuzzy2** [comment]
I noticed the “homedecor flint and steel” is actually different. It creates fake fire instead of fire. So it's not trash, actually.
Maybe just use a different name (**user-visible name only!**) and a new inventory image and a different craft, if needed.

New names could be “Fake Fire Creator” or “Magic Fire Starter” or whatever you like. ;-)

**Comment by VanessaE** [comment]
There actually wasn't much that needed done to fix this; I was able to rework the fake fire mod a little to take advantage of mt_game features.  See commit 9d2704c0c2f0db99399c30fdae035011ac90e950

**Comment by Wuzzy2** [comment]
> modifies default ice block so that it can be "ignited" (ice fire on top) with mt_game flint/steel

lol

**Comment by VanessaE** [comment]
That's how it worked in the original mod, :smile:  it just used a different flint and steel item.
