### ISSUE TITLE
2 nodes with identical name: Picture Frame

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/homedecor_modpack#377]
There are 2 nodes with an identical name: The “Picture Frame”.
Names (actually: `description`s) should be unique, if possible. It is possible in this case.

**Comment by VanessaE** [comment]
What are the node names?

**Comment by Wuzzy2** [comment]
You *could* have found them in 5 seconds in Creative, but, oh well. ;-)

`homedecor:picture_frame1`
`homedecor:picture_frame2`

**Comment by VanessaE** [comment]
78ec2119f6794cbe36d687d16241e1fee70b87df
