### ISSUE TITLE
Soda machine not subtracting gold coins (infinite soda)

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/homedecor_modpack#381]
I recently noticed that on my non-creative servers, the soda machine isn't subtracting gold coins from your inventory when you use them. Regardless of the number of coins in the slot, they are not removed from your inventory when you use it, giving you infinite amounts of soda from the machine. This shouldn't be the case, on non-creative servers at least, upon use of a coin it should disappear from your inventory when the soda is dispensed, not remain in the inventory and give you infinite sodas.

**Comment by VanessaE** [comment]
d7a4054dda87c3e155b8a4adfcaf21a5bb60803c
