### ISSUE TITLE
More items with identical names

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/homedecor_modpack#382]
I found a couple of more items with equal `description`.

The following pairs exist:

homedecor:deckchair
homedecor:deckchair_striped_blue

homedecor:curtain
homedecor:curtain_open

homedecor:shrubbery_green
homedecor:shrubbery_large_green

homedecor:shrubbery_yellow
homedecor:shrubbery_large_yellow

homedecor:shrubbery_red
homedecor:shrubbery_large_red

PS: Please merge the German translation first to avoid messing up everything again.

**Comment by VanessaE** [comment]
Fixed (in three commits).
