### ISSUE TITLE
Can't rotate all ways

### ISSUE THREAD

**Issue by Billre** [minetest-mods/homedecor_modpack#383]
I had made an upside down house about a year ago and added home decor items.  With the revised mod, I've needed to redo many items in the house but I can't turn the lamps and chairs upside down anymore.

**Comment by VanessaE** [comment]
Yeah there are a few things that lost the ability to be flipped upside down, in the process of converting over to param2 colorization.  It can't be helped - it partly an engine limitation.  I tried to limit what items I did that with though.

Still, a small price to pay for wide color range.

**Comment by Billre** [comment]
Would it be possible to make the kitchen chairs flippable?  They aren't colored

**Comment by VanessaE** [comment]
I think the wooden-only ones can already flip over, but the ones with the wool seats cannot be.

**Comment by VanessaE** [comment]
Nope, looks like they are all from the same base model, so none can be flipped over.

**Comment by Billre** [comment]
Would an upside down furniture mod be hard to make?

**Comment by VanessaE** [comment]
That would be fairly easy but definitely outside the scope of Home Decor.

**Comment by Billre** [comment]
Right - that's why I was thinking a totally separate mod.   I haven't done mods yet, but if I do, would you allow me to create a new mod with flipped versions of the items that can't be flipped in Home Decor?

**Comment by VanessaE** [comment]
You're welcome to copy/paste/flip as needed.

**Comment by Billre** [comment]
Thank you!  :-)
