### ISSUE TITLE
Desk fan image remains after WE move

### ISSUE THREAD

**Issue by Billre** [minetest-mods/homedecor_modpack#384]
When I move the homedecor:desk_fan with WorldEdit, it leaves behind an image of itself that I can't remove, not even with WorldEdit.

**Comment by VanessaE** [comment]
That's because that node is one of Jordach's "hybrid" mesh nodes - it's a base node (just a little box) and an animated *entity* for the fan itself.  Select the area around the leftover pieces and do `//clearobjects`  (with *two* slashes)
