### ISSUE TITLE
A malicious player can rewrite books they do not own.

### ISSUE THREAD

**Issue by sofar** [minetest-mods/homedecor_modpack#399]
https://github.com/minetest-mods/homedecor_modpack/blob/d7a4054dda87c3e155b8a4adfcaf21a5bb60803c/homedecor/books.lua#L166

The code assumes that the player sending this form data is the owner, but any player could craft this return data. Because a player may look at any book, the `player_current_book[player_name]` value will be valid, and thus the code will erase the book and overwrite it with the malicious players' data.

**Comment by redblade7** [comment]
Wasn't this intentional? I always leave empty books in places where players can write in them.

**Comment by sofar** [comment]
Unrelated. The book can be modified without even having the book opened. The malicious player doesn't even need to be close to the book, they can be thousands of nodes away.

**Comment by VanessaE** [comment]
That the book can be modified by non-owners may be a mod bug, but that you can do so from "thousands" of nodes away is squarely an engine issue.

**Comment by sofar** [comment]
No, that is incorrect. This code makes the mistake that when the player closes the formspec, the context (with the position) isn't destroyed. That is by itself already a reasonable fix for the problem, and can be fixed in this mod. Yes, the title of the bug isn't correct, but it's still an escape, and a memory leak, even.

**Comment by sofar** [comment]
5efa9af..eabd237

**Comment by sofar** [comment]
I enforced ownership and closed the formspec code hole. Because ownership was explicitly recorded, I assume that the original intent was to enforce this and not allow others to write books, so that's what 9d4ac9b does.
