### ISSUE TITLE
player_in_bed scope bluez

### ISSUE THREAD

**Issue by retsil2** [minetest-mods/homedecor_modpack#421]
the best we can tell, it's scope-related. it looks like the variable player_in_bed, local to both minetest_game and homedecor's bed handler, is experiencing some kind of weirdness.

sleeping in minetest_game's red bed seems to work ok.

sleeping in homedecor's white bed increments player_in_bed shown in homedecor's white bed, and then decrements player_in_bed shown in minetest_game's red bed. as a result, the embedded player count climbs into negative infinity for red beds, and into positive infinity for white beds. we looked and looked and could not figure out how that's even possible :)

**Comment by bell07** [comment]
There is no proper beds-API, therefore the homedecor did copied the most beds code but shares the beds.player table.

The variable player_in_bed was removed in homedecor in https://github.com/minetest-mods/homedecor_modpack/pull/404
Same change proposed for minetest_game/beds in https://github.com/minetest/minetest_game/pull/2125

If both changes applied, the issue with out-of-sync counts is fixed.

**Comment by VanessaE** [comment]
The official repo for this project has been moved to Gitlab.  Please copy/paste/re-open your issue over there.  https://gitlab.com/VanessaE/homedecor_modpack/issues
